// components/pricing/servicePricingData.js

export const SERVICE_CATEGORIES = [
  "Logo",
  "Website",
  "Mobile App",
  "Animation",
  "Branding",
  "SEO",
  "SMM",
  "Label Design",
  "Book Cover",
  "UI/UX",
  "Video Creation",
  "Graphics Designing",
];

// ---------- LOGO ----------
export const LOGO_PACKAGES = [
  {
    title: "Logo Basic",
    price: "$49",
    desc:
      "",
    features: [
      "4 Original Logo Concepts",
      "2 Dedicated Logo Designer",
      "4 Revisions",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG Only",
      "24 - 48 Business Hours Turn Around Time",
      "MORE FEATURES",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "Logo Professional",
    price: "$199",
    desc:
      "",
    features: [
      "12 Original Logo Concepts",
      "4 Dedicated Logo Designer (Industry Specific)",
      "Unlimited Revisions",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Email Signature Design",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
      "24 - 48 Business Hours Turn Around Time",
      "MORE FEATURES",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money Back Guarantee",
      "Dedicated Account Manager",
      "24/7 Support (Email, Chat, Call, SMS, Whatsapp)",
    ],
  },
  {
    title: "Logo Elite",
    price: "$399",
    desc:
      "",
    features: [
      "Unlimited Original Logo Concepts",
      "8 Dedicated Logo Designer (Industry Specific)",
      "Unlimited Revisions",
      "Social Media Page Design",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Email Signature Design",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
      "24 - 48 Business Hours Turn Around Time",
      "MORE FEATURES",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
];

// ---------- WEBSITE ----------
export const WEBSITE_PACKAGES = [
  {
    title: "Basic Website",
    price: "$499",
    desc:
      "",
    features: [
      "3 Page Website",
      "Custom Layout Design",
      "Contact/Query Form",
      "1 Banner Design",
      "2 Stock Photos",
      "FREE Favicon Design",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Website Initial Concepts in 48 Hours",
      "Complete Design & Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "Value Added Services",
      "Mobile Responsive will be Additional $200*",
      "CMS will be Additional $250*",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    title: "Startup Website",
    price: "$899",
    desc:
      "",
    features: [
      "5 Page Website",
      "Custom Layout Design",
      "Contact/Query Form",
      "3 Banner Design",
      "5 Stock Photos",
      "FREE Favicon Design",
      "FREE Google Friendly Sitemap",
      "Unlimited Revisions",
      "Complete W3C Certified HTML",
      "Website Initial Concepts in 48 Hours",
      "Complete Design & Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "Value Added Services",
      "Mobile Responsive will be Additional $200*",
      "CMS will be Additional $250*",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    title: "Proffesional Website",
    price: "$1499",
    desc:
      "",
    features: [
      "Up to 10 Unique Pages Website",
      "CMS /Admin Panel Integration",
      "5+ Stock Photos & Banner Designs",
      "FREE Social Media Integration",
      "FREE Favicon Design",
      "FREE Google Friendly Sitemap",
      "Unlimited Revisions",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Website Initial Concepts in 48 Hours",
      "Complete Design & Deployment",
      "Custom, Interactive & Dynamic Web Design",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "Value Added Services",
      "Mobile Responsive will be Additional $200*",
      "CMS will be Additional $250*",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    title: "E-Commerce Website",
    price: "$1799",
    desc:
      "",
    features: [
      "Custom Ecommerce Website",
      "Up to 200 Products",
      "CMS /Admin Panel Integration",
      "Fully Mobile Responsive",
      "Shopping Cart Integration",
      "Payment Gateway Integration",
      "Product Listing & Management",
      "Order Management & Tracking",
      "Banner Designs",
      "Unlimited Revisions",
      "FREE Social Media Integration",
      "FREE Favicon Design",
      "FREE Google Friendly Sitemap Search Engine Submission",
      "Complete W3C Certified HTML",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    title: "Corporate Website",
    price: "$3999",
    desc:
      "",
    features: [
      "Up to 15 Unique Pages Website",
      "Custom Made, Interactive & Dynamic Design",
      "Customized WordPress or PHP Development",
      "Fully Mobile Responsive",
      "Interactive Sliding Banners",
      "Up to 10 Custom Made Banner Designs",
      "10 Stock Images",
      "Unlimited Revisions",
      "Content Management System",
      "Online Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional)",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    title: "Platinum Website",
    price: "$6999",
    desc:
      "",
    features: [
      "Up to 20 Unique Pages Website",
      "Custom Made, Interactive & Dynamic & High-End Design",
      "Customized WordPress or PHP Development",
      "Fully Mobile Responsive",
      "Interactive Sliding Banners",
      "Up to 15 Custom Made Banner Designs",
      "15 Stock Images",
      "Unlimited Revisions",
      "Content Management System",
      "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Multi Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional)",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
];

// ---------- MOBILE APP ----------
export const MOBILE_APP_PACKAGES = [
  {
    title: "App Starter",
    price: "$999",
    desc: "",
    features: [
      "iOS or Android (1 platform)",
      "Up to 5 Screens",
      "Custom UI Design",
      "Basic Authentication",
      "API Integration (Up to 3 Endpoints)",
      "Splash Screen & App Icon",
      "Bug Fixes for 30 Days",
      "2 Rounds of Revisions",
      "Project Manager Support",
      "100% Ownership Rights",
    ],
  },
  {
    title: "App Growth",
    price: "$2499",
    desc: "",
    features: [
      "iOS or Android (1 platform)",
      "Up to 12 Screens",
      "Custom UI/UX Design",
      "User Authentication & Profiles",
      "Push Notifications",
      "API / Backend Integration",
      "Basic Analytics Integration",
      "Admin Panel (Basic)",
      "3 Rounds of Revisions",
      "60 Days Post-launch Support",
      "App Store / Play Store Submission",
      "100% Ownership Rights",
    ],
  },
  {
    title: "App Premium",
    price: "$3999",
    desc: "",
    features: [
      "iOS and Android (Cross-platform)",
      "Up to 20 Screens",
      "Advanced UI/UX with Micro-animations",
      "User Roles & Permissions",
      "Real-time Features (Chat / Live Updates)*",
      "3rd-Party Integrations (Payment, Maps, etc.)",
      "Advanced Analytics & Crash Reporting",
      "Admin Dashboard (Advanced)",
      "5 Rounds of Revisions",
      "90 Days Post-launch Support",
      "App Store / Play Store Publishing",
      "Source Code & Documentation",
      "100% Ownership Rights",
    ],
  },
  {
    title: "App Enterprise",
    price: "$6999",
    desc: "",
    features: [
      "Custom Strategy & Roadmap",
      "iOS and Android (Native or Cross-platform)",
      "Unlimited Screens (within agreed scope)",
      "Custom Backend Development",
      "Complex Integrations (ERP/CRM/Custom APIs)",
      "High-level Security & Compliance",
      "CI/CD Setup (Optional)",
      "Dedicated Project Manager",
      "Dedicated QA Team",
      "6 Months Maintenance & Support",
      "Scalability & Performance Optimization",
      "Source Code, DevOps & Documentation",
      "100% Ownership Rights",
    ],
  },
];

// ---------- ANIMATION ----------
export const ANIMATION_PACKAGES = [
  {
    title: "Teaser",
    price: "$499",
    desc: "",
    features: [
      "30sec Duration",
      "Script Writing",
      "Custom Artwork",
      "Background Music",
      "HD Format Video",
      "Dedicated Support",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },
  {
    title: "Startup",
    price: "$799",
    desc: "",
    features: [
      "30sec Duration",
      "Script Writing",
      "Professional Voice-over & SFX",
      "Hand-drawn Illustrations",
      "Unlimited Revisions",
      "HD Format Video",
      "Dedicated Support",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },
  {
    title: "Classic",
    price: "$999",
    desc: "",
    features: [
      "30sec Duration",
      "Script Writing",
      "Professional Voice-over & SFX",
      "Custom 2D Characters",
      "Unlimited Revisions",
      "HD Format Video",
      "Dedicated Support",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },
  {
    title: "3D Video",
    price: "$3999",
    desc: "",
    features: [
      "2 3D Object Models",
      "Unlimited Storyboard Revisions",
      "Professional Voice - Over",
      "Background Music",
      "Exotic Animations",
      "HD Video Format",
      "6 Weeks Delivery Time",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },
];

// ---------- BRANDING ----------
export const BRANDING_PACKAGES = [
  {
    title: "Branding Startup",
    price: "$499",
    desc: "",
    features: [
      "Logo Design",
      "6 Unique Logo Concepts",
      "FREE Icon",
      "FREE Grayscale Copy",
      "Unlimited Revisions",
      "100% Ownership Right",
      "AI, PSD, EPS, GIF, BMP, JPEG, PNG Formats",
      "Print Media",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Website Design",
      "5 Pages Custom Business Website",
      "Complete Deployment",
    ],
  },
  {
    title: "Branding Plus",
    price: "$999",
    desc: "",
    features: [
      "Logo Design",
      "12 Unique Logo Concepts",
      "FREE Icon",
      "FREE Grayscale Copy",
      "Unlimited Revisions",
      "100% Ownership Right",
      "AI, PSD, EPS, GIF, BMP, JPEG, PNG Formats",
      "Print Media",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Flyer Design / Label Design",
      "Website Design",
      "Custom 5 Pages Professional Website",
      "Content Management System (WordPress)",
      "Responsive Design (Mobile Compatible)",
      "Complete Deployment",
      "Social Media Design",
      "Facebook Fanpage Splash Page + Cover Photo",
    ],
  },
  {
    title: "Branding Classic",
    price: "$1499",
    desc: "",
    features: [
      "Logo Design",
      "12 Unique Logo Concepts",
      "FREE Icon",
      "FREE Grayscale Copy",
      "Unlimited Revisions",
      "100% Ownership Right",
      "AI, PSD, EPS, GIF, BMP, JPEG, PNG Formats",
      "Print Media",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Any Product of your Choice:",
      "Bi-fold/Tri-fold Brochure / Menu Card / Corporate Profile)",
      "Website Design",
      "10+ Page Website",
      "Content Management System (WordPress/Joomla)",
      "Complete Deployment",
      "Search Engine Submission",
      "Google, Bing, Yahoo and More",
      "Social Media Design",
      "Facebook Fanpage Splash Page + Cover Photo",
      "Twitter Background Design",
      "Google+ Profile Banner",
    ],
  },
  {
    title: "Branding Ultimate",
    price: "$1999",
    desc: "",
    features: [
      "Logo Design",
      "Infinite Unique Logo Concepts",
      "FREE Icon",
      "FREE Grayscale Copy",
      "Unlimited Revisions",
      "100% Ownership Right",
      "AI, PSD, EPS, GIF, BMP, JPEG, PNG Formats",
      "Print Media",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Any Product of your Choice:",
      "Bi-fold/Tri-fold Brochure / Menu Card / Corporate Profile)",
      "Website Design",
      "10+ Page Website",
      "Content Management System (WordPress/Joomla)",
      "Responsive Design (Mobile Compatible)",
      "Complete Deployment",
      "Social Media Design",
      "Facebook Fanpage Splash Page + Cover Photo",
      "Twitter Background Design",
      "Google+ Profile Banner",
      "Complete Storyboard, VoiceOver & Animation",
    ],
  },
];

// ---------- SEO ----------
export const SEO_PACKAGES = [
  {
    title: "SEO Basic",
    price: "$199/mo",
    desc: "",
    features: [
      "Technical Audit",
      "Keyword Research (Basic)",
      "On-page Optimization",
      "Google Search Console Setup",
      "Monthly Reporting",
      "MORE FEATURES",
      "100% Satisfaction",
    ],
  },
  {
    title: "SEO Growth",
    price: "$499/mo",
    desc: "",
    features: [
      "Technical + On-page SEO",
      "Keyword Research (Advanced)",
      "Content Optimization",
      "Link Building (Starter)",
      "Monthly Reporting",
      "MORE FEATURES",
      "100% Satisfaction",
    ],
  },
  {
    title: "SEO Pro",
    price: "$999/mo",
    desc: "",
    features: [
      "Full SEO Strategy",
      "Content Plan",
      "Link Building",
      "Conversion Tracking",
      "Weekly Updates",
      "MORE FEATURES",
      "100% Satisfaction",
    ],
  },
];

// ---------- SMM ----------
export const SMM_PACKAGES = [
  {
    title: "Bronze - Monthly",
    price: "$397",
    features: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "3 Posts per Week",
      "1 Facebook Event",
      "Monthly Reporting",
      "Ad spend - Up to $50",
    ],
  },
  {
    title: "Silver- Monthly",
    price: "$597",
    features: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "4 Posts per Week",
      "2 Facebook Event",
      "Monthly Reporting",
      "Ad spend - Up to $65",
    ],
  },
  {
    title: "Gold- Monthly",
    price: "$997",
    features: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "5 Posts per Week",
      "2 Facebook Event",
      "1 Lead Generation Campaign",
      "Monthly Reporting",
      "Ad spend - Up to $120",
    ],
  },
  {
    title: "Platinum- Monthly",
    price: "$1497",
    features: [
      "Optimize FB Page",
      "1 Social Cover + Holiday Covers",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "6 Posts per Week",
      "2 Facebook Event",
      "1 Lead Generation Campaign",
      "Monthly Reporting",
      "Ad spend - Up to $170",
    ],
  },
];

// ---------- LABEL ----------
export const LABEL_PACKAGES = [
  {
    title: "Label Starter",
    price: "$99",
    desc: "",
    features: [
      "1 Label Concept",
      "2 Revisions",
      "Print-ready File",
      "MORE FEATURES",
      "100% Satisfaction",
      "Money Back Guarantee",
    ],
  },
  {
    title: "Label Pro",
    price: "$249",
    desc: "",
    features: [
      "2 Concepts",
      "Unlimited Revisions",
      "Die-line Setup",
      "Print-ready Files",
      "MORE FEATURES",
      "100% Satisfaction",
      "Money Back Guarantee",
    ],
  },
  {
    title: "Packaging Suite",
    price: "$499",
    desc: "",
    features: [
      "3 Concepts",
      "Unlimited Revisions",
      "Multiple Variants",
      "Print-ready + Source Files",
      "MORE FEATURES",
      "100% Satisfaction",
      "Money Back Guarantee",
    ],
  },
];

// ---------- BOOK COVER ----------
export const BOOK_COVER_PACKAGES = [
  {
    title: "Book Cover Basic",
    price: "$149",
    desc: "",
    features: [
      "1 Book Cover Concept",
      "2 Rounds of Revisions",
      "Front Cover Design (eBook)",
      "Royalty-free Stock Image (1)",
      "Typography & Layout Design",
      "Print-ready & Web-ready Files",
      "JPEG / PNG / PDF Formats",
      "3–4 Business Days Turnaround",
      "100% Satisfaction",
      "100% Ownership Rights",
    ],
  },
  {
    title: "Book Cover Standard",
    price: "$299",
    desc: "",
    features: [
      "2 Custom Cover Concepts",
      "Unlimited Revisions",
      "Front, Back & Spine Design",
      "Custom Illustration or Composite Imagery",
      "Royalty-free Stock Images (Up to 3)",
      "Barcode Placement (If Provided)",
      "Print-ready Files for KDP / IngramSpark / etc.",
      "Web-ready eBook Cover",
      "Source Files (PSD / AI)",
      "5–7 Business Days Turnaround",
      "100% Satisfaction",
      "100% Ownership Rights",
    ],
  },
  {
    title: "Book Cover Premium",
    price: "$499",
    desc: "",
    features: [
      "3 Bespoke Cover Concepts",
      "Unlimited Revisions",
      "Front, Back & Spine Design",
      "Custom Illustration or Photo Manipulation",
      "Royalty-free Stock Images (Unlimited within scope)",
      "Multiple Format Variations (Paperback, Hardcover, eBook)",
      "Social Media Promotion Graphics (3 Platforms)",
      "3D Mockups for Marketing",
      "Print-ready Files for Multiple Printers",
      "Source Files (PSD / AI / INDD if required)",
      "Dedicated Account Manager",
      "Priority Support",
      "100% Ownership Rights",
    ],
  },
];

// ---------- UI/UX ----------
export const UI_UX_PACKAGES = [
  {
    title: "UI/UX Starter",
    price: "$299",
    desc: "",
    features: [
      "Up to 5 Screens",
      "Wireframes Included",
      "Basic User Flow",
      "Clean Visual Interface Design",
      "Mobile or Web (One Platform)",
      "Figma Source File",
      "2 Rounds of Revisions",
      "5–7 Business Days Turnaround",
      "100% Ownership Rights",
    ],
  },
  {
    title: "UI/UX Growth",
    price: "$699",
    desc: "",
    features: [
      "Up to 12 Screens",
      "Low + High Fidelity Wireframes",
      "User Journey Mapping",
      "Responsive UI Design",
      "Design System Basics",
      "Clickable Prototype",
      "Figma Source File",
      "Unlimited Revisions",
      "Dedicated Account Manager",
      "100% Ownership Rights",
    ],
  },
  {
    title: "UI/UX Premium",
    price: "$1299",
    desc: "",
    features: [
      "Up to 25 Screens",
      "UX Research & Competitor Review",
      "Advanced User Flows",
      "High-Fidelity UI Design",
      "Full Design System",
      "Interactive Prototype",
      "Developer Handoff in Figma",
      "Unlimited Revisions",
      "Priority Support",
      "100% Ownership Rights",
    ],
  },
];

// ---------- VIDEO CREATION ----------
export const VIDEO_CREATION_PACKAGES = [
  {
    title: "Video Starter",
    price: "$399",
    desc: "",
    features: [
      "Up to 30 Seconds Duration",
      "Basic Editing",
      "Text Animations",
      "Background Music",
      "Logo Intro/Outro",
      "HD Export",
      "2 Revisions",
      "Social Media Ready Format",
      "100% Ownership Rights",
    ],
  },
  {
    title: "Video Growth",
    price: "$799",
    desc: "",
    features: [
      "Up to 60 Seconds Duration",
      "Professional Editing",
      "Motion Graphics",
      "Stock Footage Support",
      "Brand Color & Typography Styling",
      "Voice-over Sync",
      "HD / Full HD Export",
      "Unlimited Revisions",
      "Dedicated Project Manager",
      "100% Ownership Rights",
    ],
  },
  {
    title: "Video Premium",
    price: "$1499",
    desc: "",
    features: [
      "Up to 90 Seconds Duration",
      "Advanced Editing & Transitions",
      "Custom Motion Graphics",
      "Storyboard Assistance",
      "Voice-over Integration",
      "Sound Design & Music",
      "4K Export",
      "Multiple Platform Versions",
      "Unlimited Revisions",
      "Priority Support",
      "100% Ownership Rights",
    ],
  },
];

// ---------- GRAPHICS DESIGNING ----------
export const GRAPHICS_DESIGNING_PACKAGES = [
  {
    title: "Graphics Starter",
    price: "$249",
    desc: "",
    features: [
      "3 Design Concepts",
      "Social Media Post Design Set",
      "Flyer or Poster Design",
      "Brand Color Usage",
      "Print-ready Files",
      "JPEG / PNG / PDF Formats",
      "2 Revisions",
      "Fast Turnaround",
      "100% Ownership Rights",
    ],
  },
  {
    title: "Graphics Growth",
    price: "$599",
    desc: "",
    features: [
      "6 Design Concepts",
      "Social Media Creatives Bundle",
      "Brochure / Flyer / Poster Design",
      "Ad Banner Design",
      "Brand Consistency Across Assets",
      "Print-ready + Source Files",
      "Unlimited Revisions",
      "Dedicated Account Manager",
      "100% Ownership Rights",
    ],
  },
  {
    title: "Graphics Premium",
    price: "$1099",
    desc: "",
    features: [
      "10 Custom Design Concepts",
      "Full Marketing Collateral Set",
      "Social Media + Ads + Print Assets",
      "Presentation / Pitch Deck Support",
      "Advanced Creative Direction",
      "Source Files Included",
      "Unlimited Revisions",
      "Priority Support",
      "Brand Asset Organization",
      "100% Ownership Rights",
    ],
  },
];

// ---------- map category -> packages ----------
export const SERVICE_PRICING_DATA = {
  Logo: LOGO_PACKAGES,
  Website: WEBSITE_PACKAGES,
  "Mobile App": MOBILE_APP_PACKAGES,
  Animation: ANIMATION_PACKAGES,
  Branding: BRANDING_PACKAGES,
  SEO: SEO_PACKAGES,
  SMM: SMM_PACKAGES,
  "Label Design": LABEL_PACKAGES,
  "Book Cover": BOOK_COVER_PACKAGES,
  "UI/UX": UI_UX_PACKAGES,
  "Video Creation": VIDEO_CREATION_PACKAGES,
  "Graphics Designing": GRAPHICS_DESIGNING_PACKAGES,
};